# Generated by Django 3.2.7 on 2021-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='first name')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='last name')),
                ('address', models.CharField(max_length=200, null=True)),
                ('barangay', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(blank=True, verbose_name='birth date')),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('contactnumber', models.CharField(max_length=200, null=True, verbose_name='contact number')),
                ('licensenumber', models.CharField(max_length=200, null=True, verbose_name='license number')),
                ('licenseexpiry', models.DateField(null=True, verbose_name='license expiry')),
                ('licensepic', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='license picture')),
                ('specialization', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Family Medicine', 'Family Medicine')], max_length=200, null=True)),
                ('schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('employeenumber', models.CharField(max_length=200, null=True, verbose_name='employee number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
