# Generated by Django 3.2.7 on 2021-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='barangay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='licenseexpiry',
            field=models.DateField(blank=True, verbose_name='license expiry'),
        ),
        migrations.AlterField(
            model_name='account',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
