# Generated by Django 3.2.7 on 2021-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_auto_20211026_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LGUAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='employeenumber',
            field=models.CharField(max_length=200, null=True, verbose_name='employee number'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='barangay',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='contactnumber',
            field=models.CharField(max_length=200, null=True, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='licenseexpiry',
            field=models.DateField(verbose_name='license expiry'),
        ),
        migrations.AlterField(
            model_name='account',
            name='licensepic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='license picture'),
        ),
    ]
