# Generated by Django 3.2.7 on 2021-11-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211105_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='licenseexpiry',
            field=models.DateField(null=True, verbose_name='license expiry'),
        ),
    ]
