# Generated by Django 3.2.7 on 2021-10-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('barangay', models.CharField(choices=[('Alabang', 'Alabang'), ('Ayala-Alabang', 'Ayala-Alabang'), ('Bayanan', 'Bayanan'), ('Buli', 'Buli'), ('Cupang', 'Cupang'), ('Poblacion', 'Poblacion'), ('Putatan', 'Putatan'), ('Sucat', 'Sucat'), ('Tunasan', 'Tunasan')], max_length=200, null=True)),
                ('city', models.CharField(choices=[('Muntinlupa', 'Muntinlupa')], max_length=200, null=True)),
                ('numchild', models.CharField(max_length=200, null=True)),
                ('namechild', models.CharField(max_length=200, null=True)),
                ('contactnumber', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('vaccine', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
