# Generated by Django 3.2.8 on 2021-12-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('barangay', models.CharField(choices=[('Alabang', 'Alabang'), ('Ayala-Alabang', 'Ayala-Alabang'), ('Bayanan', 'Bayanan'), ('Buli', 'Buli'), ('Cupang', 'Cupang'), ('Poblacion', 'Poblacion'), ('Putatan', 'Putatan'), ('Sucat', 'Sucat'), ('Tunasan', 'Tunasan')], max_length=200, null=True)),
                ('city', models.CharField(choices=[('Muntinlupa', 'Muntinlupa')], max_length=200, null=True)),
                ('numchild', models.CharField(blank=True, max_length=200, null=True)),
                ('namechild', models.CharField(blank=True, max_length=200, null=True)),
                ('contactnumber', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('vaccine', models.CharField(choices=[('None', 'None'), ('CoronaVac (Sinovac)', 'CoronaVac (Sinovac)'), ('Gamaleya Sputnik V', 'Gamaleya Sputnik V'), ("Johnson and Johnson's Janssen", "Johnson and Johnson's Janssen"), ('Bharat BioTech', 'Bharat BioTech'), ('Moderna', 'Moderna'), ('Sinopharm', 'Sinopharm')], max_length=200, null=True)),
                ('firstdose', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('seconddose', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('fdosedate', models.DateField(blank=True, null=True)),
                ('sdosedate', models.DateField(blank=True, null=True)),
                ('telemedicine', models.CharField(choices=[('TelAventusMD', 'TelAventusMD'), ('SeeYouDoc', 'SeeYouDoc'), ('MedCheck', 'MedCheck'), ('TeliMed', 'TeliMed'), ('KonsultaMD', 'KonsultaMD'), ('CloudPx', 'CloudPx'), ('HealthNow', 'HealthNow')], max_length=200, null=True)),
                ('antigenresult', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=200, null=True)),
                ('antigendate', models.DateField(null=True)),
                ('antigenfile', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='antigenfile')),
                ('rtpcrresult', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=200, null=True)),
                ('rtpcrdate', models.DateField(null=True)),
                ('rtpcrfile', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='rtpcrfile')),
                ('xray', models.CharField(choices=[('Chest Xray', 'Chest Xray'), ('Film Array', 'Film Array')], max_length=200, null=True)),
                ('xraydate', models.DateField(null=True)),
                ('xrayfile', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='xrayfile')),
                ('status', models.CharField(choices=[('Home Isolation', 'Home Isolation'), ('For Transfer', 'For Transfer'), ('Transfer to Hospital', 'Transfer to Hospital'), ('Transfer to Isolation Facility', 'Transfer to Isolation Facility'), ('Expired', 'Expired')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('isolationfacility', models.CharField(blank=True, max_length=200, null=True)),
                ('bmiheight', models.FloatField(max_length=200, null=True)),
                ('bmiweight', models.FloatField(max_length=200, null=True)),
                ('finalbmi', models.FloatField(max_length=200, null=True)),
                ('startdate', models.DateField(null=True)),
                ('lastdate', models.DateField(null=True)),
                ('question3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('question4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('has_hypertension', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Hypertension')),
                ('has_diabetes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Diabetes')),
                ('has_heart_disease', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Heart Diseases')),
                ('has_lung_disease', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Lung Diseases')),
                ('has_gastro', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Gastrointestinal Diseases')),
                ('has_genito', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Genitourinary Diseases')),
                ('has_neuro', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Neurological Diseases')),
                ('has_cancer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Cancer')),
                ('telemed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vitalsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(null=True)),
                ('diastolic', models.IntegerField(null=True)),
                ('heartrate', models.IntegerField(null=True)),
                ('respiratoryrate', models.IntegerField(null=True)),
                ('temperature', models.FloatField(max_length=200, null=True)),
                ('painscale', models.IntegerField(null=True)),
                ('o2saturation', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Healthtracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asymptomatic', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('fever', models.CharField(max_length=200, null=True)),
                ('cough', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('generalweakness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('fatigue', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('headache', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('bodyaches', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('sorethroat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('runnynose', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('dyspnea', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('lossappetite', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('nausea', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('vomiting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('diarrhea', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('alteredmentalstate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('losssmell', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('losstaste', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('others', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctorsnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
    ]
