# Generated by Django 3.2.7 on 2021-11-29 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('barangay', models.CharField(choices=[('Alabang', 'Alabang'), ('Ayala-Alabang', 'Ayala-Alabang'), ('Bayanan', 'Bayanan'), ('Buli', 'Buli'), ('Cupang', 'Cupang'), ('Poblacion', 'Poblacion'), ('Putatan', 'Putatan'), ('Sucat', 'Sucat'), ('Tunasan', 'Tunasan')], max_length=200, null=True)),
                ('city', models.CharField(choices=[('Muntinlupa', 'Muntinlupa')], max_length=200, null=True)),
                ('numchild', models.CharField(blank=True, max_length=200, null=True)),
                ('namechild', models.CharField(blank=True, max_length=200, null=True)),
                ('contactnumber', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('vaccine', models.CharField(choices=[('CoronaVac (Sinovac)', 'CoronaVac (Sinovac)'), ('Gamaleya Sputnik V', 'Gamaleya Sputnik V'), ("Johnson and Johnson's Janssen", "Johnson and Johnson's Janssen"), ('Bharat BioTech', 'Bharat BioTech'), ('Moderna', 'Moderna'), ('Sinopharm', 'Sinopharm')], max_length=200, null=True)),
                ('firstdose', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('seconddose', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('fdosedate', models.DateField(blank=True, null=True)),
                ('sdosedate', models.DateField(blank=True, null=True)),
                ('telemedicine', models.CharField(choices=[('TelAventusMD', 'TelAventusMD'), ('SeeYouDoc', 'SeeYouDoc'), ('MedCheck', 'MedCheck'), ('TeliMed', 'TeliMed'), ('KonsultaMD', 'KonsultaMD'), ('CloudPx', 'CloudPx'), ('HealthNow', 'HealthNow')], max_length=200, null=True)),
                ('antigenresult', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=200, null=True)),
                ('antigendate', models.DateField(null=True)),
                ('antigenfile', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='antigenfile')),
                ('rtpcrresult', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=200, null=True)),
                ('rtpcrdate', models.DateField(null=True)),
                ('rtpcrfile', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='rtpcrfile')),
                ('xray', models.CharField(choices=[('Chest Xray', 'Chest Xray'), ('Film Array', 'Film Array')], max_length=200, null=True)),
                ('xraydate', models.DateField(null=True)),
                ('xrayfile', models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='xrayfile')),
                ('status', models.CharField(choices=[('For Monitoring', 'For Monitoring'), ('For Referral', 'For Referral'), ('For Transfer', 'For Transfer')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('startdate', models.DateField(null=True)),
                ('lastdate', models.DateField(null=True)),
                ('question3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('question4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('question5', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitalsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodpressure', models.CharField(max_length=200, null=True)),
                ('heartrate', models.CharField(max_length=200, null=True)),
                ('respiratoryrate', models.CharField(max_length=200, null=True)),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('painscale', models.CharField(max_length=200, null=True)),
                ('o2saturation', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Healthtracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asymptomatic', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('fever', models.CharField(max_length=200, null=True)),
                ('cough', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('generalweakness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('fatigue', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('headache', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('bodyaches', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('sorethroat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('runnynose', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('dyspnea', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('lossappetite', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('nausea', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('vomiting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('diarrhea', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('alteredmentalstate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('losssmell', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('losstaste', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('others', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctorsnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
    ]
