# Generated by Django 3.2.7 on 2021-11-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antigenfile',
            field=models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='antigenfile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rtpcrfile',
            field=models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='rtpcrfile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='xrayfile',
            field=models.ImageField(blank=True, null=True, upload_to='pic_uploads/', verbose_name='xrayfile'),
        ),
    ]
