# Generated by Django 3.2.7 on 2021-12-16 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='vitalsign',
            name='bloodpressure',
        ),
        migrations.AddField(
            model_name='patient',
            name='bmiheight',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmiweight',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='finalbmi',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Cancer'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_gastro',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Gastrointestinal Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_genito',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Genitourinary Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_heart_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Heart Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Hypertension'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_lung_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Lung Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_neuro',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=200, verbose_name='Neurological Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='telemed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='diastolic',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='systolic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Home Isolation', 'Home Isolation'), ('For Transfer', 'For Transfer'), ('Transfer to Hospital', 'Transfer to Hospital'), ('Transfer to Isolation Facility', 'Transfer to Isolation Facility'), ('Expired', 'Expired')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.CharField(choices=[('None', 'None'), ('CoronaVac (Sinovac)', 'CoronaVac (Sinovac)'), ('Gamaleya Sputnik V', 'Gamaleya Sputnik V'), ("Johnson and Johnson's Janssen", "Johnson and Johnson's Janssen"), ('Bharat BioTech', 'Bharat BioTech'), ('Moderna', 'Moderna'), ('Sinopharm', 'Sinopharm')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='heartrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='o2saturation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='painscale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='respiratoryrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
