# Generated by Django 3.2.8 on 2022-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='antigenfile',
            field=models.FileField(blank=True, null=True, upload_to='pdf_uploads/', verbose_name='antigenfile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rtpcrfile',
            field=models.FileField(blank=True, null=True, upload_to='pdf_uploads/', verbose_name='rtpcrfile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.CharField(choices=[('None', 'None'), ('CoronaVac (Sinovac)', 'CoronaVac (Sinovac)'), ('Pfizer-BioNTech', 'Pfizer-BioNTech'), ('Oxford AstraZeneca', 'Oxford AstraZeneca'), ('Gamaleya Sputnik V', 'Gamaleya Sputnik V'), ("Johnson and Johnson's Janssen", "Johnson and Johnson's Janssen"), ('Bharat BioTech', 'Bharat BioTech'), ('Moderna', 'Moderna'), ('Novavax', 'Novavax')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='xrayfile',
            field=models.FileField(blank=True, null=True, upload_to='pdf_uploads/', verbose_name='xrayfile'),
        ),
    ]
