# Generated by Django 3.2.7 on 2021-10-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20211022_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(null=True)),
                ('lastdate', models.DateField(null=True)),
                ('question3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('question4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('question5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='antigendate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='antigenresult',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rtpcrdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rtpcrresult',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sdosedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='telemedicine',
            field=models.CharField(choices=[('TelAventusMD', 'TelAventusMD'), ('SeeYouDoc', 'SeeYouDoc'), ('MedCheck', 'MedCheck'), ('TeliMed', 'TeliMed'), ('KonsultaMD', 'KonsultaMD'), ('CloudPx', 'CloudPx'), ('HealthNow', 'HealthNow')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='xray',
            field=models.CharField(choices=[('Chest Xray', 'Chest Xray'), ('Film Array', 'Film Array')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='xraydate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='healthhistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.healthhistory'),
        ),
    ]
