# Generated by Django 3.2.7 on 2021-11-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20211106_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitalsigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodpressure', models.CharField(max_length=200, null=True)),
                ('heartrate', models.CharField(max_length=200, null=True)),
                ('respiratoryrate', models.CharField(max_length=200, null=True)),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('painscale', models.CharField(max_length=200, null=True)),
                ('o2saturation', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.patient')),
            ],
        ),
    ]
