# Generated by Django 3.2.7 on 2022-01-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20211219_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='antigenfile',
            field=models.FileField(null=True, upload_to='pdf_uploads/', verbose_name='antigenfile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rtpcrfile',
            field=models.FileField(null=True, upload_to='pdf_uploads/', verbose_name='rtpcrfile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='xrayfile',
            field=models.FileField(null=True, upload_to='pdf_uploads/', verbose_name='xrayfile'),
        ),
    ]
