# Generated by Django 3.2.7 on 2021-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_remove_vitalsign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bmiheight',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmiweight',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='finalbmi',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
