# Generated by Django 3.2.7 on 2021-10-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20211022_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('For Monitoring', 'For Monitoring'), ('For Referral', 'For Referral')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
