# Generated by Django 3.2.7 on 2021-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_auto_20211203_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='heartrate',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='o2saturation',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='painscale',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='respiratoryrate',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
