# Generated by Django 3.2.7 on 2021-10-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_alter_patient_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('For Monitoring', 'For Monitoring'), ('For Referral', 'For Referral'), ('For Transfer', 'For Transfer')], max_length=200, null=True),
        ),
    ]
