# Generated by Django 3.2.7 on 2021-12-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20211209_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='bloodpressure',
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='diastolic',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='systolic',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
