# Generated by Django 3.2.7 on 2021-12-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_auto_20211209_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='diastolic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='heartrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='o2saturation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='painscale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='respiratoryrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='systolic',
            field=models.IntegerField(null=True),
        ),
    ]
