# Generated by Django 3.2.7 on 2021-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_healthtracker_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracker',
            name='others',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
