# Generated by Django 3.2.7 on 2021-11-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_alter_healthtracker_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='question5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.CharField(choices=[('CoronaVac (Sinovac)', 'CoronaVac (Sinovac)'), ('Gamaleya Sputnik V', 'Gamaleya Sputnik V'), ("Johnson and Johnson's Janssen", "Johnson and Johnson's Janssen"), ('Bharat BioTech', 'Bharat BioTech'), ('Moderna', 'Moderna'), ('Sinopharm', 'Sinopharm')], max_length=200, null=True),
        ),
    ]
