# Generated by Django 3.2.7 on 2021-10-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_rename_healthhistory_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lastdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='question3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='question4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='question5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
