# Generated by Django 3.2.7 on 2021-12-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20211209_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Home Isolation', 'Home Isolation'), ('For Referral', 'For Referral'), ('For Transfer', 'For Transfer')], max_length=200, null=True),
        ),
    ]
