# Generated by Django 3.2.7 on 2021-12-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Home Isolation', 'Home Isolation'), ('For Transfer', 'For Transfer'), ('Transfer to Hospital', 'Transfer to Hospital'), ('Transfer to Isolation Facility', 'Transfer to Isolation Facility'), ('Expired', 'Expired'), ('For Referral', 'For Referral')], max_length=200, null=True),
        ),
    ]
