# Generated by Django 3.2.7 on 2021-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20211128_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bmiheight',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmiweight',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
