# Generated by Django 3.2.7 on 2021-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_doctorsnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
