# Generated by Django 3.2.7 on 2021-12-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart', '0010_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telemed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Home Isolation', 'Home Isolation'), ('For Transfer', 'For Transfer'), ('Transfer to Hospital', 'Transfer to Hospital'), ('Transfer to Isolation Facility', 'Transfer to Isolation Facility'), ('Expired', 'Expired')], max_length=200, null=True),
        ),
    ]
