# Generated by Django 3.2.7 on 2021-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_auto_20211129_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='finalbmi',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
