# Generated by Django 3.2.7 on 2021-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_patient_finalbmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='question5',
        ),
        migrations.AddField(
            model_name='patient',
            name='has_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Cancer'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_gastro',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Gastrointestinal Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_genito',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Genitourinary Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_heart_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Heart Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Hypertension'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_lung_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Lung Diseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_neuro',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='Neurological Diseases'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Home Isolation', 'Home Isolation'), ('For Transfer', 'For Transfer'), ('Transfer to Hospital', 'Transfer to Hospital'), ('Transfer to Isolation Facility', 'Transfer to Isolation Facility'), ('Expired', 'Expired')], max_length=200, null=True),
        ),
    ]
